language: objective-c
osx_image: xcode8.3
xcode_workspace: wk1_picwall.xcworkspace
xcode_scheme: wk1_picwall

script:
  - xcodebuild -scheme wk1_picwall -workspace wk1_picwall.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.2' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)